version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
matrix:
  fast_finish: false
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
artifacts:
- path: shadowsocks-csharp\bin\x86\Release\Shadowsocks.exe
  name: Shadowsocks-release.exe
- path: shadowsocks-csharp\bin\x86\Debug\Shadowsocks.exe
  name: Shadowsocks-debug.exe
deploy:
  provider: GitHub
  tag: $(appveyor_build_version)
  release: $(appveyor_build_version)
  description: "Build version: $(appveyor_build_version)"
  artifact: shadowsocks-csharp\bin\x86\Release\Shadowsocks.exe
  draft: false
  prerelease: false
  force_update: true
  auth_token:
    secure: D6LTeQH1zPgo5/A77bCFXJiLK8wVabWrUKO2KYfMIWI8F+YJVih6d82M8NiDDIJb
  on:
    branch: master
skip_tags: true
