//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string addButton_Content {
            get {
                return ResourceManager.GetString("addButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string cancelButton_Content {
            get {
                return ResourceManager.GetString("cancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy link.
        /// </summary>
        public static string copyLinkButton_Content {
            get {
                return ResourceManager.GetString("copyLinkButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials (optional).
        /// </summary>
        public static string CredentialsOptional {
            get {
                return ResourceManager.GetString("CredentialsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Proxy.
        /// </summary>
        public static string ForwardProxy {
            get {
                return ResourceManager.GetString("ForwardProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy.
        /// </summary>
        public static string NoProxy {
            get {
                return ResourceManager.GetString("NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Not now.
        /// </summary>
        public static string notNowButton_Content {
            get {
                return ResourceManager.GetString("notNowButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string okButton_Content {
            get {
                return ResourceManager.GetString("okButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Configuration Delivery.
        /// </summary>
        public static string OnlineConfigDelivery {
            get {
                return ResourceManager.GetString("OnlineConfigDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Register all.
        /// </summary>
        public static string registerAllButton_Content {
            get {
                return ResourceManager.GetString("registerAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string removeButton_Content {
            get {
                return ResourceManager.GetString("removeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string saveButton_Content {
            get {
                return ResourceManager.GetString("saveButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Sharing.
        /// </summary>
        public static string ServerSharing {
            get {
                return ResourceManager.GetString("ServerSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following sources failed to update:\n\n.
        /// </summary>
        public static string sip008UpdateAllFailure {
            get {
                return ResourceManager.GetString("sip008UpdateAllFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated all sources!.
        /// </summary>
        public static string sip008UpdateAllSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed. See the logs for more information..
        /// </summary>
        public static string sip008UpdateFailure {
            get {
                return ResourceManager.GetString("sip008UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated the selected source!.
        /// </summary>
        public static string sip008UpdateSuccess {
            get {
                return ResourceManager.GetString("sip008UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Skip version.
        /// </summary>
        public static string skipVersionButton_Content {
            get {
                return ResourceManager.GetString("skipVersionButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5.
        /// </summary>
        public static string SOCKS5 {
            get {
                return ResourceManager.GetString("SOCKS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (sec).
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all.
        /// </summary>
        public static string updateAllButton_Content {
            get {
                return ResourceManager.GetString("updateAllButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string updateButton_Content {
            get {
                return ResourceManager.GetString("updateButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the release notes carefully. Then decide whether to update..
        /// </summary>
        public static string updatePromptBody {
            get {
                return ResourceManager.GetString("updatePromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available..
        /// </summary>
        public static string updatePromptTitle {
            get {
                return ResourceManager.GetString("updatePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionUpdate.
        /// </summary>
        public static string VersionUpdate {
            get {
                return ResourceManager.GetString("VersionUpdate", resourceCulture);
            }
        }
    }
}
